### ISSUE TITLE
Security Hub custom action

### ISSUE THREAD

**Issue by Abdu0007** [gabrielsoltz/metahub#82]
deployed lambda and tried to execute metahub for findings using Security Hub custom action. However, lambda is not enriched back with the context for the finding. 
![image](https://github.com/gabrielsoltz/metahub/assets/100774980/02f97174-7c22-4133-a97f-6ccb6cd389ca)

Nothing happened in the event
![image](https://github.com/gabrielsoltz/metahub/assets/100774980/399d4675-162b-4cdb-8d50-20f2db34d1d4)

**Comment by gabrielsoltz** [comment]
Hi @Abdu0007, are you using the Terraform code provided by the tool for deploying the Custom Action + Lambda resources? Is the lambda being executed after triggering the Security Hub action? Do you have any errors as part of the Lambda function?

**Comment by Abdu0007** [comment]
hi @gabrielsoltz , yes. I'm using the provided terraform. There was no error when I applied the terraform. The lambda is not executed after triggering the security hub custom action. However. when I tested the lambda manually it executed successfully.
![image](https://github.com/gabrielsoltz/metahub/assets/100774980/9d0ea26e-6b77-4e17-bb20-e602dfda27ab)

**Comment by gabrielsoltz** [comment]
hey @Abdu0007 sorry that this took me so long, busy days... 

I tested MetaHub in a new environment from scratch, just in case, and it is working as expected. 

Could you please double check if the lambda is executing after the Custom Action, check the Cloudwatch LogGroup (/aws/lambda/metahub-lambda) to see if there is any execution. 

You don't need to create any automation rules. 

The only thing you need to do, as explained in the [documentation](https://github.com/gabrielsoltz/metahub?tab=readme-ov-file#run-with-security-hub-custom-action), is manually enable the enrich mode. 
> By default, no action will be taken on the findings, but you can change this behavior. See [Customize Lambda behavior](https://github.com/gabrielsoltz/metahub?tab=readme-ov-file#customize-lambda-behaviour).

You can do this by uncommenting this code: https://github.com/gabrielsoltz/metahub/blob/main/lib/lambda.py#L14-L17

**Comment by gabrielsoltz** [comment]
Hi @Abdu0007 can I close this issue?

**Comment by Abdu0007** [comment]
Hi @gabrielsoltz, yes, you can.

**Comment by Abdu0007** [comment]
Hi @gabrielsoltz, yes, you can.
